if(ANDROID)
    set(SDL_SHARED ON CACHE BOOL "shared")
    set(SDL_STATIC ON CACHE BOOL "static")
    add_subdirectory(libsrc/SDL2-2.0.12 EXCLUDE_FROM_ALL)
    add_library(SDL2::SDL2 ALIAS SDL2)
else()
    set(SDL_SHARED OFF CACHE BOOL "no shared")
    set(SDL_STATIC ON CACHE BOOL "static")
    set(SDL_STATIC_PIC ON CACHE BOOL "Static version of the library should be built with Position Independent Code")
    set(SDL_SHARED OFF)
    set(SDL_STATIC ON)
    set(SDL_STATIC_PIC ON)
    set(FORCE_STATIC_VCRT ON CACHE BOOL "static windows static vcrc")
    add_subdirectory(libsrc/SDL2-2.0.12 EXCLUDE_FROM_ALL)
    add_library(SDL2::SDL2 ALIAS SDL2-static)
endif(ANDROID)
add_library(SDL2::SDL2main ALIAS SDL2main)
