
set(SAVED_BUILD_SHARED_LIBS "${BUILD_SHARED_LIBS}")
set(SAVED_CMAKE_DISABLE_FIND_PACKAGE_ZLIB_LIBS "${CMAKE_DISABLE_FIND_PACKAGE_ZLIB}")
set(SAVED_CMAKE_DISABLE_FIND_PACKAGE_BZip2_LIBS "${CMAKE_DISABLE_FIND_PACKAGE_BZip2}")
set(SAVED_CMAKE_DISABLE_FIND_PACKAGE_PNG_LIBS "${CMAKE_DISABLE_FIND_PACKAGE_PNG}")
set(SAVED_CMAKE_DISABLE_FIND_PACKAGE_HarfBuzz "${CMAKE_DISABLE_FIND_PACKAGE_HarfBuzz}")
set(SAVED_CMAKE_DISABLE_FIND_PACKAGE_BrotliDec "${CMAKE_DISABLE_FIND_PACKAGE_BrotliDec}")

set(SAVED_BUILD_SHARED_LIBS OFF)
set(CMAKE_DISABLE_FIND_PACKAGE_ZLIB ON)
set(CMAKE_DISABLE_FIND_PACKAGE_BZip2 ON)
set(CMAKE_DISABLE_FIND_PACKAGE_PNG ON)
set(CMAKE_DISABLE_FIND_PACKAGE_HarfBuzz ON)
set(CMAKE_DISABLE_FIND_PACKAGE_BrotliDec ON)

add_subdirectory(Common/libsrc/freetype-2.10.4   EXCLUDE_FROM_ALL)
add_library(FreeType::FreeType ALIAS freetype)

set(SAVED_BUILD_SHARED_LIBS "${SAVED_BUILD_SHARED_LIBS}")
set(CMAKE_DISABLE_FIND_PACKAGE_ZLIB "${SAVED_CMAKE_DISABLE_FIND_PACKAGE_ZLIB_LIBS}")
set(CMAKE_DISABLE_FIND_PACKAGE_BZip2 "${SAVED_CMAKE_DISABLE_FIND_PACKAGE_BZip2_LIBS}")
set(CMAKE_DISABLE_FIND_PACKAGE_PNG "${SAVED_CMAKE_DISABLE_FIND_PACKAGE_PNG_LIBS}")
set(CMAKE_DISABLE_FIND_PACKAGE_HarfBuzz "${SAVED_CMAKE_DISABLE_FIND_PACKAGE_HarfBuzz}")
set(CMAKE_DISABLE_FIND_PACKAGE_BrotliDec "${SAVED_CMAKE_DISABLE_FIND_PACKAGE_BrotliDec}")
